# Generated by Django 4.2.1 on 2023-05-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('30mg', '30mg'), ('50mg', '50mg'), ('100mg', '100mg')], default='None', max_length=10),
        ),
    ]
